//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CommandLine.g4 by ANTLR 4.9.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Bulka.CommandLine {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.1")]
[System.CLSCompliant(false)]
public partial class CommandLineLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, Int2=5, Rgb=6, Rgba=7, Boolean=8, Integer=9, 
		Real=10, DoubleQuotedString=11, SingleQuotedString=12, Word=13, ShortHexRgbColor=14, 
		ShortHexRgbaColor=15, LongHexRgbColor=16, LongHexRgbaColor=17, Whitespace=18;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "Int2", "Rgb", "Rgba", "Boolean", "Integer", 
		"Real", "DoubleQuotedString", "SingleQuotedString", "Word", "ShortHexRgbColor", 
		"ShortHexRgbaColor", "LongHexRgbColor", "LongHexRgbaColor", "HexDigit", 
		"Whitespace"
	};


	public CommandLineLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public CommandLineLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "';'", "'('", "','", "')'", "'int2'", "'rgb'", "'rgba'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, "Int2", "Rgb", "Rgba", "Boolean", "Integer", 
		"Real", "DoubleQuotedString", "SingleQuotedString", "Word", "ShortHexRgbColor", 
		"ShortHexRgbaColor", "LongHexRgbColor", "LongHexRgbaColor", "Whitespace"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "CommandLine.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static CommandLineLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x14', '\xB7', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x5', '\t', 'T', '\n', '\t', '\x3', '\n', '\x5', 
		'\n', 'W', '\n', '\n', '\x3', '\n', '\x6', '\n', 'Z', '\n', '\n', '\r', 
		'\n', '\xE', '\n', '[', '\x3', '\v', '\x5', '\v', '_', '\n', '\v', '\x3', 
		'\v', '\a', '\v', '\x62', '\n', '\v', '\f', '\v', '\xE', '\v', '\x65', 
		'\v', '\v', '\x3', '\v', '\x3', '\v', '\x6', '\v', 'i', '\n', '\v', '\r', 
		'\v', '\xE', '\v', 'j', '\x3', '\v', '\x6', '\v', 'n', '\n', '\v', '\r', 
		'\v', '\xE', '\v', 'o', '\x3', '\v', '\x5', '\v', 's', '\n', '\v', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\a', '\f', 'y', '\n', '\f', 
		'\f', '\f', '\xE', '\f', '|', '\v', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\a', '\r', '\x84', '\n', 
		'\r', '\f', '\r', '\xE', '\r', '\x87', '\v', '\r', '\x3', '\r', '\x3', 
		'\r', '\x3', '\xE', '\x3', '\xE', '\a', '\xE', '\x8D', '\n', '\xE', '\f', 
		'\xE', '\xE', '\xE', '\x90', '\v', '\xE', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', 
		'\x6', '\x14', '\xB2', '\n', '\x14', '\r', '\x14', '\xE', '\x14', '\xB3', 
		'\x3', '\x14', '\x3', '\x14', '\x2', '\x2', '\x15', '\x3', '\x3', '\x5', 
		'\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', 
		'\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', '\xE', 
		'\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '!', '\x12', '#', '\x13', 
		'%', '\x2', '\'', '\x14', '\x3', '\x2', '\f', '\b', '\x2', '-', '-', '/', 
		'/', 'h', 'h', 'p', 'p', 'v', 'v', '{', '{', '\x3', '\x2', '\x32', ';', 
		'\a', '\x2', '$', '$', '^', '^', 'p', 'p', 't', 't', 'v', 'v', '\x5', 
		'\x2', '\x2', '!', '$', '$', '^', '^', '\a', '\x2', ')', ')', '^', '^', 
		'p', 'p', 't', 't', 'v', 'v', '\x5', '\x2', '\x2', '!', ')', ')', '^', 
		'^', '\x4', '\x2', '\x43', '\\', '\x63', '|', '\x6', '\x2', '/', '\x30', 
		'\x32', ';', '\x43', '\\', '\x63', '|', '\x5', '\x2', '\x32', ';', '\x43', 
		'H', '\x63', 'h', '\x5', '\x2', '\v', '\f', '\xF', '\xF', '\"', '\"', 
		'\x2', '\xC8', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x3', ')', '\x3', '\x2', '\x2', 
		'\x2', '\x5', '+', '\x3', '\x2', '\x2', '\x2', '\a', '-', '\x3', '\x2', 
		'\x2', '\x2', '\t', '/', '\x3', '\x2', '\x2', '\x2', '\v', '\x31', '\x3', 
		'\x2', '\x2', '\x2', '\r', '\x36', '\x3', '\x2', '\x2', '\x2', '\xF', 
		':', '\x3', '\x2', '\x2', '\x2', '\x11', 'S', '\x3', '\x2', '\x2', '\x2', 
		'\x13', 'V', '\x3', '\x2', '\x2', '\x2', '\x15', '^', '\x3', '\x2', '\x2', 
		'\x2', '\x17', 't', '\x3', '\x2', '\x2', '\x2', '\x19', '\x7F', '\x3', 
		'\x2', '\x2', '\x2', '\x1B', '\x8A', '\x3', '\x2', '\x2', '\x2', '\x1D', 
		'\x91', '\x3', '\x2', '\x2', '\x2', '\x1F', '\x96', '\x3', '\x2', '\x2', 
		'\x2', '!', '\x9C', '\x3', '\x2', '\x2', '\x2', '#', '\xA4', '\x3', '\x2', 
		'\x2', '\x2', '%', '\xAE', '\x3', '\x2', '\x2', '\x2', '\'', '\xB1', '\x3', 
		'\x2', '\x2', '\x2', ')', '*', '\a', '=', '\x2', '\x2', '*', '\x4', '\x3', 
		'\x2', '\x2', '\x2', '+', ',', '\a', '*', '\x2', '\x2', ',', '\x6', '\x3', 
		'\x2', '\x2', '\x2', '-', '.', '\a', '.', '\x2', '\x2', '.', '\b', '\x3', 
		'\x2', '\x2', '\x2', '/', '\x30', '\a', '+', '\x2', '\x2', '\x30', '\n', 
		'\x3', '\x2', '\x2', '\x2', '\x31', '\x32', '\a', 'k', '\x2', '\x2', '\x32', 
		'\x33', '\a', 'p', '\x2', '\x2', '\x33', '\x34', '\a', 'v', '\x2', '\x2', 
		'\x34', '\x35', '\a', '\x34', '\x2', '\x2', '\x35', '\f', '\x3', '\x2', 
		'\x2', '\x2', '\x36', '\x37', '\a', 't', '\x2', '\x2', '\x37', '\x38', 
		'\a', 'i', '\x2', '\x2', '\x38', '\x39', '\a', '\x64', '\x2', '\x2', '\x39', 
		'\xE', '\x3', '\x2', '\x2', '\x2', ':', ';', '\a', 't', '\x2', '\x2', 
		';', '<', '\a', 'i', '\x2', '\x2', '<', '=', '\a', '\x64', '\x2', '\x2', 
		'=', '>', '\a', '\x63', '\x2', '\x2', '>', '\x10', '\x3', '\x2', '\x2', 
		'\x2', '?', '@', '\a', 'v', '\x2', '\x2', '@', '\x41', '\a', 't', '\x2', 
		'\x2', '\x41', '\x42', '\a', 'w', '\x2', '\x2', '\x42', 'T', '\a', 'g', 
		'\x2', '\x2', '\x43', '\x44', '\a', 'h', '\x2', '\x2', '\x44', '\x45', 
		'\a', '\x63', '\x2', '\x2', '\x45', '\x46', '\a', 'n', '\x2', '\x2', '\x46', 
		'G', '\a', 'u', '\x2', '\x2', 'G', 'T', '\a', 'g', '\x2', '\x2', 'H', 
		'I', '\a', '{', '\x2', '\x2', 'I', 'J', '\a', 'g', '\x2', '\x2', 'J', 
		'T', '\a', 'u', '\x2', '\x2', 'K', 'L', '\a', 'p', '\x2', '\x2', 'L', 
		'T', '\a', 'q', '\x2', '\x2', 'M', 'N', '\a', 'q', '\x2', '\x2', 'N', 
		'T', '\a', 'p', '\x2', '\x2', 'O', 'P', '\a', 'q', '\x2', '\x2', 'P', 
		'Q', '\a', 'h', '\x2', '\x2', 'Q', 'T', '\a', 'h', '\x2', '\x2', 'R', 
		'T', '\t', '\x2', '\x2', '\x2', 'S', '?', '\x3', '\x2', '\x2', '\x2', 
		'S', '\x43', '\x3', '\x2', '\x2', '\x2', 'S', 'H', '\x3', '\x2', '\x2', 
		'\x2', 'S', 'K', '\x3', '\x2', '\x2', '\x2', 'S', 'M', '\x3', '\x2', '\x2', 
		'\x2', 'S', 'O', '\x3', '\x2', '\x2', '\x2', 'S', 'R', '\x3', '\x2', '\x2', 
		'\x2', 'T', '\x12', '\x3', '\x2', '\x2', '\x2', 'U', 'W', '\a', '/', '\x2', 
		'\x2', 'V', 'U', '\x3', '\x2', '\x2', '\x2', 'V', 'W', '\x3', '\x2', '\x2', 
		'\x2', 'W', 'Y', '\x3', '\x2', '\x2', '\x2', 'X', 'Z', '\t', '\x3', '\x2', 
		'\x2', 'Y', 'X', '\x3', '\x2', '\x2', '\x2', 'Z', '[', '\x3', '\x2', '\x2', 
		'\x2', '[', 'Y', '\x3', '\x2', '\x2', '\x2', '[', '\\', '\x3', '\x2', 
		'\x2', '\x2', '\\', '\x14', '\x3', '\x2', '\x2', '\x2', ']', '_', '\a', 
		'/', '\x2', '\x2', '^', ']', '\x3', '\x2', '\x2', '\x2', '^', '_', '\x3', 
		'\x2', '\x2', '\x2', '_', 'r', '\x3', '\x2', '\x2', '\x2', '`', '\x62', 
		'\t', '\x3', '\x2', '\x2', '\x61', '`', '\x3', '\x2', '\x2', '\x2', '\x62', 
		'\x65', '\x3', '\x2', '\x2', '\x2', '\x63', '\x61', '\x3', '\x2', '\x2', 
		'\x2', '\x63', '\x64', '\x3', '\x2', '\x2', '\x2', '\x64', '\x66', '\x3', 
		'\x2', '\x2', '\x2', '\x65', '\x63', '\x3', '\x2', '\x2', '\x2', '\x66', 
		'h', '\a', '\x30', '\x2', '\x2', 'g', 'i', '\t', '\x3', '\x2', '\x2', 
		'h', 'g', '\x3', '\x2', '\x2', '\x2', 'i', 'j', '\x3', '\x2', '\x2', '\x2', 
		'j', 'h', '\x3', '\x2', '\x2', '\x2', 'j', 'k', '\x3', '\x2', '\x2', '\x2', 
		'k', 's', '\x3', '\x2', '\x2', '\x2', 'l', 'n', '\t', '\x3', '\x2', '\x2', 
		'm', 'l', '\x3', '\x2', '\x2', '\x2', 'n', 'o', '\x3', '\x2', '\x2', '\x2', 
		'o', 'm', '\x3', '\x2', '\x2', '\x2', 'o', 'p', '\x3', '\x2', '\x2', '\x2', 
		'p', 'q', '\x3', '\x2', '\x2', '\x2', 'q', 's', '\a', '\x30', '\x2', '\x2', 
		'r', '\x63', '\x3', '\x2', '\x2', '\x2', 'r', 'm', '\x3', '\x2', '\x2', 
		'\x2', 's', '\x16', '\x3', '\x2', '\x2', '\x2', 't', 'z', '\a', '$', '\x2', 
		'\x2', 'u', 'v', '\a', '^', '\x2', '\x2', 'v', 'y', '\t', '\x4', '\x2', 
		'\x2', 'w', 'y', '\n', '\x5', '\x2', '\x2', 'x', 'u', '\x3', '\x2', '\x2', 
		'\x2', 'x', 'w', '\x3', '\x2', '\x2', '\x2', 'y', '|', '\x3', '\x2', '\x2', 
		'\x2', 'z', 'x', '\x3', '\x2', '\x2', '\x2', 'z', '{', '\x3', '\x2', '\x2', 
		'\x2', '{', '}', '\x3', '\x2', '\x2', '\x2', '|', 'z', '\x3', '\x2', '\x2', 
		'\x2', '}', '~', '\a', '$', '\x2', '\x2', '~', '\x18', '\x3', '\x2', '\x2', 
		'\x2', '\x7F', '\x85', '\a', ')', '\x2', '\x2', '\x80', '\x81', '\a', 
		'^', '\x2', '\x2', '\x81', '\x84', '\t', '\x6', '\x2', '\x2', '\x82', 
		'\x84', '\n', '\a', '\x2', '\x2', '\x83', '\x80', '\x3', '\x2', '\x2', 
		'\x2', '\x83', '\x82', '\x3', '\x2', '\x2', '\x2', '\x84', '\x87', '\x3', 
		'\x2', '\x2', '\x2', '\x85', '\x83', '\x3', '\x2', '\x2', '\x2', '\x85', 
		'\x86', '\x3', '\x2', '\x2', '\x2', '\x86', '\x88', '\x3', '\x2', '\x2', 
		'\x2', '\x87', '\x85', '\x3', '\x2', '\x2', '\x2', '\x88', '\x89', '\a', 
		')', '\x2', '\x2', '\x89', '\x1A', '\x3', '\x2', '\x2', '\x2', '\x8A', 
		'\x8E', '\t', '\b', '\x2', '\x2', '\x8B', '\x8D', '\t', '\t', '\x2', '\x2', 
		'\x8C', '\x8B', '\x3', '\x2', '\x2', '\x2', '\x8D', '\x90', '\x3', '\x2', 
		'\x2', '\x2', '\x8E', '\x8C', '\x3', '\x2', '\x2', '\x2', '\x8E', '\x8F', 
		'\x3', '\x2', '\x2', '\x2', '\x8F', '\x1C', '\x3', '\x2', '\x2', '\x2', 
		'\x90', '\x8E', '\x3', '\x2', '\x2', '\x2', '\x91', '\x92', '\a', '%', 
		'\x2', '\x2', '\x92', '\x93', '\x5', '%', '\x13', '\x2', '\x93', '\x94', 
		'\x5', '%', '\x13', '\x2', '\x94', '\x95', '\x5', '%', '\x13', '\x2', 
		'\x95', '\x1E', '\x3', '\x2', '\x2', '\x2', '\x96', '\x97', '\a', '%', 
		'\x2', '\x2', '\x97', '\x98', '\x5', '%', '\x13', '\x2', '\x98', '\x99', 
		'\x5', '%', '\x13', '\x2', '\x99', '\x9A', '\x5', '%', '\x13', '\x2', 
		'\x9A', '\x9B', '\x5', '%', '\x13', '\x2', '\x9B', ' ', '\x3', '\x2', 
		'\x2', '\x2', '\x9C', '\x9D', '\a', '%', '\x2', '\x2', '\x9D', '\x9E', 
		'\x5', '%', '\x13', '\x2', '\x9E', '\x9F', '\x5', '%', '\x13', '\x2', 
		'\x9F', '\xA0', '\x5', '%', '\x13', '\x2', '\xA0', '\xA1', '\x5', '%', 
		'\x13', '\x2', '\xA1', '\xA2', '\x5', '%', '\x13', '\x2', '\xA2', '\xA3', 
		'\x5', '%', '\x13', '\x2', '\xA3', '\"', '\x3', '\x2', '\x2', '\x2', '\xA4', 
		'\xA5', '\a', '%', '\x2', '\x2', '\xA5', '\xA6', '\x5', '%', '\x13', '\x2', 
		'\xA6', '\xA7', '\x5', '%', '\x13', '\x2', '\xA7', '\xA8', '\x5', '%', 
		'\x13', '\x2', '\xA8', '\xA9', '\x5', '%', '\x13', '\x2', '\xA9', '\xAA', 
		'\x5', '%', '\x13', '\x2', '\xAA', '\xAB', '\x5', '%', '\x13', '\x2', 
		'\xAB', '\xAC', '\x5', '%', '\x13', '\x2', '\xAC', '\xAD', '\x5', '%', 
		'\x13', '\x2', '\xAD', '$', '\x3', '\x2', '\x2', '\x2', '\xAE', '\xAF', 
		'\t', '\n', '\x2', '\x2', '\xAF', '&', '\x3', '\x2', '\x2', '\x2', '\xB0', 
		'\xB2', '\t', '\v', '\x2', '\x2', '\xB1', '\xB0', '\x3', '\x2', '\x2', 
		'\x2', '\xB2', '\xB3', '\x3', '\x2', '\x2', '\x2', '\xB3', '\xB1', '\x3', 
		'\x2', '\x2', '\x2', '\xB3', '\xB4', '\x3', '\x2', '\x2', '\x2', '\xB4', 
		'\xB5', '\x3', '\x2', '\x2', '\x2', '\xB5', '\xB6', '\b', '\x14', '\x2', 
		'\x2', '\xB6', '(', '\x3', '\x2', '\x2', '\x2', '\x11', '\x2', 'S', 'V', 
		'[', '^', '\x63', 'j', 'o', 'r', 'x', 'z', '\x83', '\x85', '\x8E', '\xB3', 
		'\x3', '\x2', '\x3', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Bulka.CommandLine
